apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: log-output:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
